version: '3.2'
services:
  mysql:
    image: adilmehmoodbutt/mariadb-server10.5-opencart:new
    container_name: mysql
    hostname: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=opencart
      - MYSQL_ROOT_PASSWORD=change_to_secure_password
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: change_to_secure_password

  opencart:
    image: adilmehmoodbutt/opencart-3.0.3.6
    container_name: opencart
    hostname: opencart
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./opencart_html:/var/www
    depends_on:
      - mysql
volumes:
  mysql_data:
    driver: local
  opencart_html:
    driver: local
